// <auto-generated />
namespace BomacApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Check : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Check));
        
        string IMigrationMetadata.Id
        {
            get { return "201911051446593_Check"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
